name: device-master-data-dp-training-env
version: v1beta
entity: product
type: data
tags:
  - DPDomain.Network
  - DPUsecase.Device Failure Prediction
  - DPTier.Source Aligned
description: A data product that monitors modem performance by tracking resource utilization, hardware health, signal strength, and error occurrences over time.

v1beta:
  data:
    meta:
      title: Device Master Data training dp
      sourceCodeUrl: https://github.com/Siva1316/Device_Telemetry/tree/main/device_master_data
 
    collaborators:
      - name: acies05
        description: owner
    
    resource:
      refType: dataos
      ref: bundle:v1beta:device-master-data-bundle-trng-env

    inputs:
      - refType: dataos
        ref:  dataos://postgresdeviceteledepot:public/device_master_data

      - refType: dataos
        ref:  dataos://postgresdeviceteledepot:public/customer_info

      - refType: dataos
        ref:  dataos://postgresdeviceteledepot:public/customer_support_feedback

    outputs:
      - refType: dataos
        ref: dataos://lakehouse:siva/device_master_data

      - refType: dataos
        ref: dataos://lakehouse:siva/customer_info

      - refType: dataos
        ref: dataos://lakehouse:siva/customer_support_feedback

        
