views:
  - name: device_usage
    description: "This view provides insights into customer credit risk, transactions, and credit behavior."
    public: true
    meta:
      title: device_usage_metrics
      tags:
        - DPDomain.Network  
        - DPUsecase.Device Failure Prediction
        - DPTier.Consumer Aligned 
      metric:
        expression: "*/45 * * * *"
        timezone: "UTC"
        window: "day"

    tables:
      - join_path: device_master_data
        prefix: true
        includes:
          - device_id
          - region_name
          - timestamps

      - join_path: device_master_data
        prefix: true
        includes: 
          - os_update_title   
          - bios_version
          - os_name
          - os_version
          - driver_status
          - satisfaction_score
          - network_latency
             
     